// Run: NODE_PATH=<directory containing playwright> node tests/composer.spec.cjs
// Uses installed Edge and isolated synthetic map responses; never opens user datasets.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const artifacts = fs.mkdtempSync(path.join(os.tmpdir(), 'GeoNex-composer-'));

(async () => {
    const browser = await chromium.launch({ channel: 'msedge', headless: true });
    const page = await browser.newPage({ viewport: { width: 1366, height: 768 }, acceptDownloads: true });
    const errors = [];
    page.on('dialog', dialog=>dialog.accept());
    page.on('pageerror', e => errors.push(e.message));
    let assertions = 0;
    const check = (value, expected, label) => { assert.deepEqual(value, expected, label); assertions++; };
    try {
        const razor = fs.readFileSync(path.join(root, 'GeoNex/Components/Pages/PrintComposer.razor'), 'utf8');
        const css = fs.readFileSync(path.join(root, 'GeoNex/wwwroot/css/composer.css'), 'utf8');
        await page.setContent(`<style>${css}</style><div class="composer-overlay"><header class="composer-header"><h2>Compositor — teste isolado</h2></header>
            <div class="composer-workspace"><aside class="composer-toolbar"></aside><main class="composer-canvas-area" id="composer-canvas-area">
            <div id="composer-paper-holder"><div class="paper-sheet" id="paper-sheet" data-width-mm="297" data-height-mm="210" style="width:${297*96/25.4}px;height:${210*96/25.4}px"></div></div>
            </main><aside class="composer-properties">Propriedades do layout</aside></div></div>`);
        await page.addScriptTag({ path: path.join(root, 'GeoNex/wwwroot/js/composer_v2.js') });
        await page.addScriptTag({ path: path.join(root, 'GeoNex/wwwroot/js/composer_document.js'), type:'module' });
        await page.evaluate(() => {
            window.calls = [];
            window.helper = { invokeMethodAsync: async (...args) => {
                calls.push(args);
                if (args[0] === 'OnItemSelected' && args[1].Type === 'Legend') composerUpdateItemProperty(args[1].Id, 'LegendItems', JSON.stringify([
                    { Name: '<img src=x onerror=alert(1)>', Color: '#226677', BorderColor: '#000000', IsVisible: true }
                ]));
            } };
            composerInitV3('paper-sheet', helper, 'http://127.0.0.1:9999/');
        });
        check(await page.evaluate(() => composerExportGeometry(297,210,300).width), 3508, 'A4 landscape 300 DPI');
        check(await page.evaluate(() => composerExportGeometry(420,297,150).height), 1754, 'A3 150 DPI');
        check(await page.evaluate(() => { try { composerExportGeometry(1189,841,300); return false; } catch { return true; } }), true, 'A0 budget');
        check(await page.evaluate(() => { try { composerExportGeometry(NaN,210,300); return false; } catch { return true; } }), true, 'NaN rejected');
        const id = await page.evaluate(() => composerAddItemV3('Text', 'Título cartográfico', 45, 40, 420, 60));
        await page.evaluate(id => { composerUpdateItemProperty(id,'FontSize',28); composerUpdateItemProperty(id,'FontFamily','Times New Roman'); composerUpdateItemProperty(id,'X',100); }, id);
        await page.evaluate(() => composerUndo());
        check(await page.$eval('#'+id, i => parseFloat(i.style.left)), 45, 'undo property');
        await page.evaluate(() => composerUndo(true));
        check(await page.$eval('#'+id, i => parseFloat(i.style.left)), 100, 'redo property');
        await page.click('#'+id);
        check(await page.evaluate(() => calls.filter(c => c[0] === 'OnLayoutChanged').at(-1)[1][0].FontSize), 28, 'selection preserves properties');
        await page.evaluate(id => { composerCopyItem(id); composerPasteItem(); }, id);
        check(await page.locator('.composer-item').count(), 2, 'duplicate');
        check(await page.locator('.composer-item').last().locator('.item-content').evaluate(i => i.style.fontFamily), '"Times New Roman"', 'duplicate style');
        await page.evaluate(id => { composerSelectItem(id); composerUpdateItemProperty(id,'Locked',true); composerDeleteItem(id); composerUpdateItemProperty(id,'X',900); }, id);
        check(await page.$eval('#'+id, i => parseFloat(i.style.left)), 100, 'locked position');
        check(await page.locator('.composer-item').count(), 2, 'locked deletion blocked');
        await page.evaluate(id => composerDeleteItem([...document.querySelectorAll('.composer-item')].find(i => i.id !== id).id), id);
        await page.evaluate(id => { composerUpdateItemProperty(id,'Locked',false); composerSelectItem(id); }, id);
        await page.keyboard.press('ArrowRight');
        check(await page.$eval('#'+id, i => Math.round(parseFloat(i.style.left)*1000)), Math.round((100+96/25.4)*1000), 'keyboard millimeters');
        await page.evaluate(id => composerUpdateItemProperty(id,'Visible',false), id);
        check(await page.$eval('#'+id, i => i.style.display), 'none', 'hidden');
        await page.evaluate(() => composerUndo());
        check(await page.$eval('#'+id, i => i.style.display !== 'none'), true, 'undo visibility');
        const legend = await page.evaluate(() => composerAddItemV3('Legend', '<svg onload=alert(1)>', 500,100,250,150));
        check(await page.locator('#'+legend+' .item-content img, #'+legend+' .item-content svg').count(), 0, 'legend escapes HTML');
        await page.evaluate(() => composerSetGuides(true));
        const before = await page.$eval('#'+id, i => parseFloat(i.style.left));
        await page.evaluate(id => composerSelectItem(id), id);
        const box = await page.locator('#'+id).boundingBox();
        await page.mouse.move(box.x+20,box.y+20); await page.mouse.down(); await page.mouse.move(box.x+49,box.y+38); await page.mouse.up();
        check(await page.$eval('#'+id, i => Math.abs(parseFloat(i.style.left)/(5*96/25.4)-Math.round(parseFloat(i.style.left)/(5*96/25.4))) < 1e-4), true, 'grid snap');
        assert.notEqual(await page.$eval('#'+id, i => parseFloat(i.style.left)), before); assertions++;
        await page.evaluate(() => composerUndo());
        check(await page.$eval('#'+id, i => parseFloat(i.style.left)), before, 'gesture is one undo step');
        await page.evaluate(id => { composerSelectItem(id); composerAlignItem('center'); }, id);
        check(await page.$eval('#'+id, i => Math.round(parseFloat(i.style.left))), Math.round((297*96/25.4-420)/2), 'page alignment');

        // Exercise actual browser renderers, not just a stubbed export function.
        await page.addScriptTag({ url:'https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js' });
        await page.addScriptTag({ url:'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js' });
        await page.evaluate(() => { composerSetWorkspaceZoom(.3); composerSetGuides(true); });
        const original = await page.$eval('#paper-sheet', i => i.outerHTML);
        const pngDownload = page.waitForEvent('download');
        await page.evaluate(() => composerExportPNG('layout.png',150));
        const png = await pngDownload; await png.saveAs(path.join(artifacts,'layout.png'));
        const bytes = fs.readFileSync(path.join(artifacts,'layout.png'));
        check([bytes.readUInt32BE(16),bytes.readUInt32BE(20)], [1754,1240], 'actual PNG dimensions');
        const phys = bytes.indexOf(Buffer.from('pHYs'));
        check(bytes.readUInt32BE(phys+4), Math.round(150/.0254), 'PNG DPI metadata');
        check(await page.$eval('#paper-sheet', i => i.outerHTML), original, 'export preserves zoom/selection/guides');
        await page.evaluate(() => { const p=document.getElementById('paper-sheet'); p.dataset.widthMm=420; p.dataset.heightMm=297; p.style.width=(420*96/25.4)+'px'; p.style.height=(297*96/25.4)+'px'; composerPageChanged(); });
        const pdfDownload = page.waitForEvent('download');
        await page.evaluate(() => composerExportPDF('layout-A3.pdf',96));
        const pdf = await pdfDownload; await pdf.saveAs(path.join(artifacts,'layout-A3.pdf'));
        const pdfText=fs.readFileSync(path.join(artifacts,'layout-A3.pdf')).toString('latin1');
        const media=pdfText.match(/\/MediaBox \[0 0 ([\d.]+) ([\d.]+)\]/);
        check(media.slice(1).map(n => Math.round(Number(n)*25.4/72)), [420,297], 'actual PDF A3 page');
        await page.screenshot({ path:path.join(artifacts,'workspace.png') });
        await page.evaluate(id => composerUpdateItemProperty(id,'X',-100), id);
        check(await page.evaluate(async () => { try { await composerExportPNG('overflow.png',96); return false; } catch(e) { return e.message.includes('fora da página'); } }), true, 'off-page preflight');
        await page.evaluate(() => composerUndo());
        await page.route('http://127.0.0.1:9999/**', route => route.fulfill({
            status:200, contentType:'image/svg+xml', headers:{'Access-Control-Allow-Origin':'*'},
            body:'<svg xmlns="http://www.w3.org/2000/svg" width="800" height="400"><rect width="800" height="400" fill="#b8d9c0"/><path d="M0 100L800 250M250 0L300 400" stroke="#537c90" stroke-width="12"/></svg>'
        }));
        const mapOk = await page.evaluate(() => composerAddItemV3('Map','Mapa sintético',40,200,400,200));
        const north = await page.evaluate(() => composerAddItemV3('Image','Norte de quadrícula',600,250,50,80));
        const context = { crsName:'SIRGAS 2000 / UTM 23S',token:'fixture-token',metersPerUnit:1,centerX:10,centerY:20,originX:500000,originY:7400000,cssZoom:96/.0254/5000,scale:5000 };
        await page.evaluate(([id,context])=>composerUseProjectView(id,context),[mapOk,context]);
        check(await page.$eval('#'+mapOk+' img',i=>new URL(i.src).searchParams.get('cs')),'5000','scale transmitted to renderer');
        check(await page.$eval('#'+mapOk+' img',i=>new URL(i.src).searchParams.get('ct')),'fixture-token','CRS/origin token transmitted');
        const bar = await page.evaluate(()=>composerAddItemV3('ScaleBar','Escala',600,360,300,50));
        const barWidth = await page.locator('#'+bar+' .item-content > div').evaluate(i=>parseFloat(i.style.width));
        check(Math.round(barWidth*25.4/96),20,'100 meters at 1:5000 = 20 mm');
        await page.evaluate(id=>composerUpdateItemProperty(id,'MapScale',10000),mapOk);
        check(await page.locator('#'+bar+' .item-content > div').evaluate(i=>Math.round(parseFloat(i.style.width)*25.4/96)),10,'bar follows map scale');
        await page.evaluate(()=>composerUndo());
        check(await page.locator('#'+bar+' .item-content > div').evaluate(i=>Math.round(parseFloat(i.style.width)*25.4/96)),20,'scale and bar undo together');
        const viewBefore = await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.mapView));
        await page.evaluate(id=>{composerSelectItem(id);composerSetMapInteractionModeV3(true);},mapOk);
        const mapBox = await page.locator('#'+mapOk).boundingBox();
        await page.mouse.move(mapBox.x+30,mapBox.y+30);await page.mouse.down();await page.mouse.move(mapBox.x+60,mapBox.y+45);await page.mouse.up();
        check(await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.mapView).scale),5000,'pan preserves denominator');
        assert.notEqual(await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.mapView).centerX),viewBefore.centerX); assertions++;
        await page.evaluate(()=>{composerUndo();composerSetMapInteractionModeV3(false);});
        await page.evaluate(id=>composerUpdateItemProperty(id,'Width',400.333),mapOk);
        check(await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.mapView).scale),5000,'resize preserves denominator');
        check(await page.$eval('#'+mapOk+' img',i=>new URL(i.src).searchParams.get('cw')),'400.333','fractional physical width transmitted');
        check(await page.evaluate(()=>{try{composerScaleToZoom(5000,0);return false;}catch{return true;}}),true,'degrees rejected in JS');
        check(await page.evaluate(()=>{try{composerScaleToZoom(-1,1);return false;}catch{return true;}}),true,'negative scale rejected in JS');
        await page.evaluate(([north,map])=>{composerLinkNorth(north,map,true);composerUpdateItemProperty(map,'MapRotation',25);},[north,mapOk]);
        check(await page.$eval('#'+north,i=>i.style.transform),'rotate(-25deg)','linked north matches renderer rotation sign');
        await page.evaluate(()=>composerUndo());
        check(await page.$eval('#'+north,i=>i.style.transform),'rotate(0deg)','map and north undo atomically');
        const mapStart=await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.mapView));
        check(await page.evaluate(id=>composerMapAction(id,'remember'),mapOk),true,'remember map view');
        await page.evaluate(id=>composerMapAction(id,'n',100),mapOk);
        check(await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.mapView).centerY),mapStart.centerY-100,'north uses inverted local Y');
        await page.evaluate(id=>composerMapAction(id,'restore'),mapOk);
        check(await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.mapView)),mapStart,'restore remembered map');
        await page.evaluate(id=>composerMapAction(id,'ne',100),mapOk);
        check(await page.$eval('#'+mapOk,(i,start)=>{const v=JSON.parse(i.dataset.mapView);return Math.round(Math.hypot(v.centerX-start.centerX,v.centerY-start.centerY));},mapStart),100,'diagonal total distance');
        await page.evaluate(()=>composerUndo());
        check(await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.mapView)),mapStart,'map pan undo');
        await page.evaluate(id=>composerMapAction(id,'factor',2),mapOk);
        check(await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.mapView).scale),10000,'map factor denominator');
        check(await page.locator('#'+bar+' .item-content > div').evaluate(i=>Math.round(parseFloat(i.style.width)*25.4/96)),10,'map tools update scale bar');
        await page.evaluate(id=>composerMapAction(id,'width',1000),mapOk);
        check(await page.$eval('#'+mapOk,i=>Math.round(JSON.parse(i.dataset.mapView).scale*parseFloat(i.style.width)*.0254/96)),1000,'coverage width metres');
        await page.evaluate(id=>composerMapAction(id,'rotate',90),mapOk);
        check(await page.$eval('#'+north,i=>i.style.transform),'rotate(-90deg)','map tools update north');
        await page.evaluate(id=>composerMapAction(id,'north'),mapOk);
        check(await page.$eval('#'+north,i=>i.style.transform),'rotate(0deg)','north up');
        const reference=await page.evaluate(context=>{const id=composerAddItemV3('Map','Referência',100,100,600,300);composerUseProjectView(id,context);return id;},context);
        check(await page.evaluate(([id,src])=>composerMapAction(id,'extent',0,src),[mapOk,reference]),true,'contain other extent');
        check(await page.$eval('#'+mapOk,i=>Math.round(JSON.parse(i.dataset.mapView).scale)),7500,'contain adjusts aspect ratios');
        await page.evaluate(([id,src])=>composerMapAction(id,'view',0,src),[mapOk,reference]);
        check(await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.mapView).scale),5000,'copy map view');
        await page.evaluate(id=>{const i=document.getElementById(id),v=JSON.parse(i.dataset.mapView);v.token='incompatible';i.dataset.mapView=JSON.stringify(v);},reference);
        check(await page.evaluate(([id,src])=>composerMapAction(id,'view',0,src),[mapOk,reference]),false,'incompatible map rejected');
        await page.evaluate(id=>composerDeleteItem(id),reference);
        check(await page.evaluate(id=>composerMapAction(id,'factor',NaN),mapOk),false,'nonfinite map factor rejected');
        await page.evaluate(id=>composerUpdateItemProperty(id,'Locked',true),mapOk);
        check(await page.evaluate(id=>composerMapAction(id,'e',100),mapOk),false,'locked map action rejected');
        await page.evaluate(id=>{composerUpdateItemProperty(id,'Locked',false);composerUpdateItemProperty(id,'MapPreviewDpi',.5);},mapOk);
        check(await page.$eval('#'+mapOk+' img',i=>new URL(i.src).searchParams.get('dpi')),'0.5','light preview resolution');
        check(await page.evaluate(()=>composerValidateLayout(composerSerializeLayout()).items.find(i=>i.type==='Map').properties.MapPreviewDpi),.5,'preview resolution persists');
        const gridGeometry=await page.evaluate(()=>{
            const v={originX:500000,originY:7400000,centerX:0,centerY:0,scale:96/.0254,metersPerUnit:1};
            const p={GridAuto:false,GridIntervalX:50,GridIntervalY:50};
            const zero=composerBuildGrid(v,400,200,0,p),rot=composerBuildGrid(v,400,200,90,p);
            return {x:zero.lines.find(l=>l.axis===0&&l.value===500050).hits.map(h=>Math.round(h.x)),y:zero.lines.find(l=>l.axis===1&&l.value===7400050).hits.map(h=>Math.round(h.y)),rot:rot.lines.find(l=>l.axis===0&&l.value===500050).hits.map(h=>Math.round(h.y)),labels:zero.svg.includes('7400050')};
        });
        check(gridGeometry,{x:[250,250],y:[50,50],rot:[50,50],labels:true},'grid absolute coordinates and renderer rotation');
        check(await page.evaluate(()=>composerBuildGrid({originX:0,originY:0,centerX:0,centerY:0,scale:5000,metersPerUnit:1},400,200,0,{GridAuto:false,GridIntervalX:.00001,GridIntervalY:.00001}).warning.length>0),true,'dense grid bounded');
        check(await page.evaluate(()=>composerBuildGrid({centerX:0,centerY:0,scale:5000,metersPerUnit:1},400,200,0).warning.length>0),true,'missing origin rejected');
        check(await page.evaluate(()=>composerBuildGrid({originX:0,originY:0,centerX:0,centerY:0,scale:5000,metersPerUnit:0},400,200,0).warning.length>0),true,'geographic grid rejected');
        await page.evaluate(id=>composerUpdateItemProperty(id,'GridEnabled',true),mapOk);
        check(await page.locator('#'+mapOk+' .composer-grid-image').count(),1,'grid overlay created');
        await page.evaluate(()=>composerUndo());
        check(await page.locator('#'+mapOk+' .composer-grid-image').count(),0,'grid toggle undo');
        await page.evaluate(id=>{composerUpdateItemProperty(id,'GridEnabled',true);composerUpdateItemProperty(id,'GridMode','cross');},mapOk);
        check(await page.$eval('#'+mapOk+' .composer-grid-image',i=>i.src.startsWith('data:image/svg+xml')),true,'grid exportable SVG image');
        const gridBefore=await page.$eval('#'+mapOk+' .composer-grid-image',i=>i.src);
        await page.evaluate(id=>composerMapAction(id,'n',40),mapOk);
        check(await page.$eval('#'+mapOk+' .composer-grid-image',(i,before)=>i.src!==before,gridBefore),true,'grid follows map pan');
        await page.evaluate(id=>{composerUpdateItemProperty(id,'GridMode','lines');composerUpdateItemProperty(id,'GridPrecision',1);},mapOk);
        const gridSaved=await page.evaluate(()=>composerSerializeLayout());
        check(await page.evaluate(s=>composerValidateLayout(s).items.find(i=>i.type==='Map').properties.GridPrecision,gridSaved),1,'grid settings persist');
        check(await page.evaluate(s=>{const d=JSON.parse(s);d.items.find(i=>i.type==='Map').view.originX++;try{composerValidateLayout(JSON.stringify(d));return false;}catch{return true;}},gridSaved),true,'forged origin rejected');
        await page.evaluate(s=>composerImportLayout(s),gridSaved);
        check(await page.locator('#'+mapOk+' .composer-grid-image').count(),1,'grid regenerated after import');
        check(await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.mapView).originY),7400000,'absolute grid origin roundtrip');
        const secondGrid=await page.evaluate(id=>composerGridAction(id,'add','grid_legacy'),mapOk);
        check(typeof secondGrid,'string','add independent grid');
        await page.evaluate(([id,g])=>{composerGridAction(id,'update',g,'GridMode','cross');composerGridAction(id,'update',g,'GridLabels',false);composerGridAction(id,'update',g,'GridTicks',false);composerGridAction(id,'update',g,'GridColor','#9b584a');},[mapOk,secondGrid]);
        check(await page.locator('#'+mapOk+' .composer-grid-image').count(),2,'two grid overlays');
        check(await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.grids).map(g=>g.GridMode)),['lines','cross'],'independent grid modes');
        await page.evaluate(([id,g])=>composerGridAction(id,'up',g),[mapOk,secondGrid]);
        check(await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.grids)[0].GridMode),'cross','grid order');
        await page.evaluate(()=>composerUndo());
        check(await page.$eval('#'+mapOk,i=>JSON.parse(i.dataset.grids)[0].GridMode),'lines','grid order undo');
        const duplicateGrid=await page.evaluate(([id,g])=>composerGridAction(id,'duplicate',g),[mapOk,secondGrid]);
        check(await page.locator('#'+mapOk+' .composer-grid-image').count(),3,'duplicate grid');
        await page.evaluate(([id,g])=>composerGridAction(id,'remove',g),[mapOk,duplicateGrid]);
        check(await page.locator('#'+mapOk+' .composer-grid-image').count(),2,'remove grid');
        await page.evaluate(id=>{for(const [p,v] of Object.entries({GridLabelPosition:'outside',GridLabelOrientation:'border',GridLabelDistance:6,GridLabelFormat:'number',GridLabelColor:'#123d72'}))composerGridAction(id,'update','grid_legacy',p,v);},mapOk);
        check(await page.$eval('#'+mapOk+' [data-grid-id="grid_legacy"]',i=>parseFloat(i.style.left)<0),true,'outside coordinates are not clipped by map frame');
        check(await page.$eval('#'+mapOk+' [data-grid-id="grid_legacy"]',i=>decodeURIComponent(i.src).includes('rotate(-90)')),true,'coordinates follow vertical edge');
        const multiSaved=await page.evaluate(()=>composerSerializeLayout());
        check(await page.evaluate(s=>composerValidateLayout(s).items.find(i=>i.type==='Map').grids.length,multiSaved),2,'multiple grids validated');
        check(await page.evaluate(s=>{const d=JSON.parse(s),g=d.items.find(i=>i.type==='Map').grids;g[1].Id=g[0].Id;try{composerValidateLayout(JSON.stringify(d));return false;}catch{return true;}},multiSaved),true,'duplicate grid ids rejected');
        await page.evaluate(s=>composerImportLayout(s),multiSaved);
        check(await page.locator('#'+mapOk+' .composer-grid-image').count(),2,'multiple grids import');
        await page.evaluate(id=>composerUpdateItemProperty(id,'Locked',true),mapOk);
        check(await page.evaluate(id=>composerGridAction(id,'add',''),mapOk),null,'locked map grid protected');
        await page.evaluate(id=>composerUpdateItemProperty(id,'Locked',false),mapOk);
        const labelChecks=await page.evaluate(()=>{
            const v={originX:500000,originY:7400000,centerX:0,centerY:0,scale:5000,metersPerUnit:1},occupied=[];
            const first=composerBuildGrid(v,400,200,25,{GridLabelPosition:'outside',GridLabelAxes:'x'},occupied);
            const second=composerBuildGrid(v,400,200,25,{GridLabelPosition:'outside',GridLabelAxes:'x'},occupied);
            return [first.labels.every(l=>l.text.startsWith('X ')),second.labels.length===0,first.labels.some(l=>l.box.x<0||l.box.y<0||l.box.x+l.box.w>400||l.box.y+l.box.h>200)];
        });
        check(labelChecks,[true,true,true],'axis filter and cross-grid collision prevention');
        check(await page.evaluate(id=>composerGridAction(id,'update','grid_legacy','GridLabelPosition','invalid'),mapOk),null,'invalid grid label options rejected');
        for(let i=0;i<6;i++)await page.evaluate(id=>composerGridAction(id,'add',''),mapOk);
        check(await page.evaluate(id=>composerGridAction(id,'add',''),mapOk),null,'eight grid limit');
        await page.evaluate(s=>composerImportLayout(s),multiSaved);
        await page.evaluate(id=>composerUpdateItemProperty(id,'X',0),mapOk);
        check(await page.evaluate(()=>composerAudit(150).some(i=>i.message.includes('Coordenadas da grade fora'))),true,'external labels outside page caught');
        await page.evaluate(()=>composerUndo());
        const preview = await page.$eval('#'+mapOk+' img',i=>i.src);
        const mapDownload = page.waitForEvent('download');
        await page.evaluate(()=>composerExportPNG('layout-map.png',150));
        await (await mapDownload).saveAs(path.join(artifacts,'layout-map.png'));
        const gridPdf=page.waitForEvent('download');
        await page.evaluate(()=>composerExportPDF('layout-grid.pdf',150));
        await (await gridPdf).saveAs(path.join(artifacts,'layout-grid.pdf'));
        check(await page.$eval('#'+mapOk+' img',i=>i.src),preview,'export preserves map preview URL');
        check(await page.locator('.composer-export-surface').count(),0,'export surface disposed');
        await page.evaluate(([map,north,bar])=>{composerDeleteItem(bar);composerDeleteItem(north);composerDeleteItem(map);},[mapOk,north,bar]);
        await page.unroute('http://127.0.0.1:9999/**');
        await page.route('http://127.0.0.1:9999/**', route => route.abort());
        const map = await page.evaluate(() => composerAddItemV3('Map','Mapa sem servidor',40,200,400,200));
        check(await page.evaluate(async () => { try { await composerExportPNG('must-not-exist.png',96); return false; } catch { return true; } }), true, 'failed map blocks export');
        check(await page.locator('.composer-export-surface').count(),0,'failure surface disposed');
        await page.evaluate(id => composerDeleteItem(id), map);
        // Disposal and re-entry must not duplicate shortcuts or retain old references.
        await page.evaluate(() => { composerDispose(); document.getElementById('paper-sheet').replaceChildren(); composerInitV3('paper-sheet',helper,null); });
        const fresh = await page.evaluate(() => composerAddItemV3('Text','Nova sessão',40,40,200,60));
        await page.keyboard.press('ArrowRight');
        check(await page.$eval('#'+fresh,i=>Math.round(parseFloat(i.style.left)*1000)), Math.round((40+96/25.4)*1000), 'one listener after re-init');
        const frameBefore=await page.$eval('#'+fresh,i=>[i.style.left,i.style.top,i.style.width,i.style.height]);
        await page.evaluate(id=>composerApplyAppearance(id,'accent'),fresh);
        check(await page.$eval('#'+fresh,i=>i.style.backgroundColor),'rgb(232, 245, 250)','accent preset fill');
        check(await page.$eval('#'+fresh,i=>[i.style.left,i.style.top,i.style.width,i.style.height]),frameBefore,'appearance preserves geometry');
        await page.evaluate(()=>composerUndo());
        check(await page.$eval('#'+fresh,i=>i.style.getPropertyValue('--composer-frame')),'','preset undoes atomically');
        await page.evaluate(id=>{composerApplyAppearance(id,'paper');composerUpdateItemProperty(id,'BorderStyle','dashed');composerUpdateItemProperty(id,'Name','Elemento principal');},fresh);
        check(await page.$eval('#'+fresh,i=>getComputedStyle(i,'::after').borderTopStyle),'dashed','dashed frame rendered');
        check(await page.$eval('#'+fresh,i=>i.dataset.text),'Nova sessão','name does not overwrite printed text');
        await page.evaluate(id=>composerUpdateItemProperty(id,'Opacity',5),fresh);
        check(await page.$eval('#'+fresh,i=>i.style.opacity),'1','opacity bounded');
        await page.evaluate(id=>composerUpdateItemProperty(id,'Rotation',450),fresh);
        check(await page.$eval('#'+fresh,i=>i.style.transform),'rotate(90deg)','rotation normalized');
        await page.evaluate(id=>composerUpdateItemProperty(id,'Rotation',0),fresh);
        const ellipse=await page.evaluate(()=>composerAddItemV3('Ellipse','Forma',100,100,200,100));
        await page.evaluate(id=>{composerUpdateItemProperty(id,'BorderStyle','dotted');composerUpdateItemProperty(id,'HasBg',false);},ellipse);
        check(await page.$eval('#'+ellipse+' .item-content',i=>i.style.borderTopStyle),'dotted','shape border style');
        check(await page.$eval('#'+ellipse+' .item-content',i=>i.style.backgroundColor),'transparent','shape fill switch');
        await page.evaluate(id=>composerDeleteItem(id),ellipse);
        check(await page.evaluate(id=>composerCopyAppearance(id),fresh),true,'copy appearance');
        const target=await page.evaluate(()=>composerAddItemV3('Text','Destino',100,100,200,100));
        check(await page.evaluate(id=>composerPasteAppearance(id),target),true,'paste appearance');
        check(await page.$eval('#'+target,i=>[i.dataset.borderStyle,i.dataset.text,i.style.width]),['dashed','Destino','200px'],'paste preserves content and dimensions');
        await page.evaluate(()=>composerUndo());
        check(await page.$eval('#'+target,i=>i.dataset.borderStyle || ''),'','paste atomic undo');
        check(await page.evaluate(id=>composerResizeFrame(id,'percent',150),target),true,'resize percentage');
        check(await page.$eval('#'+target,i=>[i.style.left,i.style.top,i.style.width,i.style.height]),['50px','75px','300px','150px'],'resize preserves center and aspect');
        await page.evaluate(()=>composerUndo());
        check(await page.$eval('#'+target,i=>i.style.width),'200px','resize atomic undo');
        check(await page.evaluate(id=>composerResizeFrame(id,'percent',NaN),target),false,'invalid percent rejected');
        await page.evaluate(id=>composerUpdateItemProperty(id,'Locked',true),target);
        check(await page.evaluate(id=>composerResizeFrame(id,'fit'),target),false,'locked resize rejected');
        check(await page.evaluate(id=>composerPasteAppearance(id),target),false,'locked paste rejected');
        await page.evaluate(id=>{composerUpdateItemProperty(id,'Locked',false);composerUpdateItemProperty(id,'Rotation',45);composerResizeFrame(id,'fit');},target);
        check(await page.$eval('#'+target,i=>{
            const p=i.parentElement,m=10*96/25.4,x=parseFloat(i.style.left),y=parseFloat(i.style.top),w=parseFloat(i.style.width),h=parseFloat(i.style.height);
            return x>=m-0.01 && y>=m-0.01 && x+w<=parseFloat(p.style.width)-m+0.01 && y+h<=parseFloat(p.style.height)-m+0.01 && Math.abs(w/h-2)<1e-6 && i.style.transform==='rotate(0deg)';
        }),true,'fit inside margins with preserved aspect and reset rotation');
        await page.evaluate(id=>composerDeleteItem(id),target);
        await page.evaluate(id=>{
            composerUpdateItemProperty(id,'LineHeight',1.8);composerUpdateItemProperty(id,'LetterSpacing',2);
            composerUpdateItemProperty(id,'TextDecoration','underline');composerUpdateItemProperty(id,'TextTransform','uppercase');
        },fresh);
        check(await page.$eval('#'+fresh+' .item-content',i=>[i.style.lineHeight,i.style.letterSpacing,i.style.textDecoration,i.style.textTransform]),['1.8','2px','underline','uppercase'],'advanced typography rendered');
        check(await page.$eval('#'+fresh,i=>i.dataset.text),'Nova sessão','case transform preserves source text');
        await page.evaluate(id=>composerUpdateItemProperty(id,'LineHeight',NaN),fresh);
        check(await page.$eval('#'+fresh+' .item-content',i=>i.style.lineHeight),'1.8','nonfinite typography rejected');
        check(await page.evaluate(id=>composerRepeatItem(id,2,2,5,7),fresh),true,'create repeat matrix');
        check(await page.locator('.composer-item').count(),4,'matrix counts original');
        check(await page.evaluate(()=>new Set([...document.querySelectorAll('.composer-item')].map(i=>i.id)).size),4,'matrix ids unique');
        check(await page.evaluate(()=>{const i=[...document.querySelectorAll('.composer-item')];return Math.abs(parseFloat(i[1].style.left)-parseFloat(i[0].style.left)-200-5*96/25.4)<.001;}),true,'matrix spacing mm');
        await page.evaluate(()=>composerUndo());
        check(await page.locator('.composer-item').count(),1,'matrix single undo');
        check(await page.evaluate(id=>composerRepeatItem(id,9,9,0,0),fresh),false,'matrix limits');
        const advancedLegend=await page.evaluate(()=>{
            const id=composerAddItemV3('Legend','LEGENDA',40,180,550,250);
            composerUpdateItemProperty(id,'LegendItems',JSON.stringify(['Zonas','Água','Estradas','Parques'].map(Name=>({Name,Color:'#68a89b',BorderColor:'#263d4e',IsVisible:true}))));
            for(const [p,v] of Object.entries({LegendColumns:2,LegendFontSize:16,LegendTitleSize:22,LegendRowGap:12,LegendColumnGap:16,LegendSymbolWidth:25,LegendSymbolHeight:10})) composerUpdateItemProperty(id,p,v);
            return id;
        });
        check(await page.$eval('#'+advancedLegend+' .item-content strong',i=>i.style.fontSize),'22px','legend title size');
        check(await page.$eval('#'+advancedLegend+' .item-content > div > div',i=>[i.style.width,i.style.marginBottom,i.style.paddingRight]),['50%','12px','16px'],'legend columns spacing');
        check(await page.$eval('#'+advancedLegend+' .item-content > div > div > span',i=>[i.style.width,i.style.height]),['25px','10px'],'legend symbol dimensions');
        await page.evaluate(id=>composerLegendAction(id,'sort'),advancedLegend);
        check(await page.$eval('#'+advancedLegend,i=>JSON.parse(i.dataset.legendData).map(r=>r.Name)),['Água','Estradas','Parques','Zonas'],'legend alphabetic order');
        await page.evaluate(id=>composerLegendAction(id,'down',0),advancedLegend);
        check(await page.$eval('#'+advancedLegend,i=>JSON.parse(i.dataset.legendData)[1].Name),'Água','legend move down');
        await page.evaluate(id=>composerLegendAction(id,'hide'),advancedLegend);
        check(await page.locator('#'+advancedLegend+' .item-content > div > div').count(),0,'legend hide all');
        await page.evaluate(()=>composerUndo());
        check(await page.locator('#'+advancedLegend+' .item-content > div > div').count(),4,'legend visibility undo');
        await page.evaluate(id=>composerUpdateItemProperty(id,'LegendHideTitle',true),advancedLegend);
        check(await page.$eval('#'+advancedLegend+' strong',i=>i.style.display),'none','legend hide title');
        await page.evaluate(id=>composerUpdateItemProperty(id,'LegendHideTitle',false),advancedLegend);
        const advancedSaved=await page.evaluate(()=>composerSerializeLayout());
        check(await page.evaluate(s=>composerValidateLayout(s).items.find(i=>i.type==='Legend').properties.LegendColumns,advancedSaved),2,'advanced properties validate');
        await page.evaluate(s=>composerImportLayout(s),advancedSaved);
        check(await page.$eval('#'+advancedLegend+' .item-content strong',i=>i.style.fontSize),'22px','advanced legend restored');
        const advancedDownload=page.waitForEvent('download');
        await page.evaluate(()=>composerExportPNG('advanced-tools.png',96));
        await (await advancedDownload).saveAs(path.join(artifacts,'advanced-tools.png'));
        await page.evaluate(id=>composerDeleteItem(id),advancedLegend);
        const styleDownload=page.waitForEvent('download');
        await page.evaluate(()=>composerExportPNG('inspector-style.png',96));
        await (await styleDownload).saveAs(path.join(artifacts,'inspector-style.png'));
        const saved=await page.evaluate(()=>composerSerializeLayout());
        check(await page.evaluate(text=>composerValidateLayout(text).items.length,saved),1,'layout schema roundtrip');
        await page.evaluate(()=>composerApplyTemplate('technical',[]));
        check(await page.locator('.composer-item').count(),5,'technical template without fake metric bar in unknown CRS');
        check(await page.evaluate(()=>composerAudit(96).some(i=>i.message.includes('texto de exemplo'))),true,'audit flags placeholders');
        await page.evaluate(()=>composerUndo());
        check(await page.locator('.composer-item').count(),1,'template is one undo operation');
        const invalid=JSON.parse(saved);invalid.items[0].properties.FontFamily='Arial; background:url(https://invalid.example)';
        check(await page.evaluate(text=>{try{composerValidateLayout(text);return false;}catch{return true;}},JSON.stringify(invalid)),true,'import rejects injected style');
        const duplicate=JSON.parse(saved);duplicate.items.push(duplicate.items[0]);
        check(await page.evaluate(text=>{try{composerValidateLayout(text);return false;}catch{return true;}},JSON.stringify(duplicate)),true,'import rejects duplicate IDs');
        const prevCount=await page.locator('.composer-item').count();
        check(await page.evaluate(async text=>{try{await composerImportLayout(text);return false;}catch{return true;}},JSON.stringify(invalid)),true,'invalid import fails');
        check(await page.locator('.composer-item').count(),prevCount,'invalid import leaves document intact');
        await page.evaluate(()=>{const p=document.getElementById('paper-sheet');p.dataset.widthMm=210;p.dataset.heightMm=297;p.style.width=210*96/25.4+'px';p.style.height=297*96/25.4+'px';composerPageChanged();});
        await page.evaluate(text=>composerImportLayout(text),saved);
        check(await page.$eval('#'+fresh,i=>JSON.parse(i.dataset.properties).Name),'Elemento principal','name roundtrip');
        check(await page.$eval('#'+fresh,i=>getComputedStyle(i,'::after').borderTopStyle),'dashed','border style roundtrip');
        check(await page.$eval('#paper-sheet',i=>Number(i.dataset.widthMm)),420,'import restores saved A3 page');
        await page.evaluate(()=>composerUndo());
        check(await page.$eval('#paper-sheet',i=>Number(i.dataset.widthMm)),210,'undo restores page settings as well as items');
        // Visual fixture of the editor chrome using the production stylesheet (not a MAUI screenshot).
        await page.evaluate(()=>{
            document.querySelector('.composer-header').innerHTML='<div class="brand-group"><div><span class="brand-eyebrow">GEONEX / LAYOUT</span><h2>Compositor de impressão</h2></div></div><div class="composer-actions"><button class="tool-btn">Painéis</button><button class="tool-btn">Ajustar</button><select class="gis-select" style="width:100px"><option>300 DPI</option></select><button class="tool-btn">Exportar Imagem</button><button class="tool-btn">Exportar PDF</button></div>';
            const tools=document.querySelector('.composer-toolbar');
            tools.innerHTML='<span class="tool-category">EDITAR</span><div class="tool-group"><button class="composer-tool active">↖ Selecionar</button><button class="composer-tool">✥ Mover mapa</button></div><div class="tool-divider"></div><span class="tool-category">INSERIR</span><div class="tool-group">'+['Mapa','Texto','Legenda','Norte','Escala','Retângulo','Elipse'].map((n,i)=>'<button class="composer-tool"><span class="shape-icon">'+['▧','T','☷','↑','↔','▭','○'][i]+'</span><span>'+n+'</span></button>').join('')+'</div>';
            const edit=document.createElement('div');edit.className='composer-editbar';edit.innerHTML='<button class="tool-btn">↶ Desfazer</button><button class="tool-btn">↷ Refazer</button><label><input type="checkbox" checked>Encaixar na grade</label><div class="editbar-divider"></div><button class="tool-btn">Duplicar</button><button class="tool-btn">Trazer à frente</button><button class="tool-btn">Enviar ao fundo</button><button class="tool-btn danger">Excluir</button>';
            document.querySelector('.composer-header').after(edit);
            document.querySelector('.composer-properties').innerHTML='<nav class="property-tabs"><button>Página</button><button>Itens</button><button class="active">Propriedades</button><button>Revisão</button></nav><div class="props-header"><h3>Propriedades do item</h3></div><div class="props-content"><div class="selection-heading"><span class="selection-badge">Map</span><span>Selecionado</span></div><label class="inspector-field inspector-name"><span>Nome no layout</span><input class="gis-input" value="Área de estudo"></label><nav class="inspector-tabs"><button>Conteúdo</button><button>Dimensões</button><button class="active">Visual</button></nav><section class="inspector-card"><h4>Estilos rápidos</h4><div class="inspector-body inspector-presets"><button><span class="preset-sample clean"></span>Limpo</button><button><span class="preset-sample paper"></span>Papel</button><button><span class="preset-sample accent"></span>Destaque</button></div></section><section class="inspector-card"><div class="inspector-switch"><h4>Preenchimento</h4><label><input type="checkbox" checked><span>Ativo</span></label></div><div class="inspector-body inspector-grid"><label class="inspector-field"><span>Cor de fundo</span><input type="color" class="gis-input color-field" value="#ffffff"></label><span class="color-value">#ffffff</span></div></section><section class="inspector-card"><div class="inspector-switch"><h4>Contorno</h4><label><input type="checkbox" checked><span>Ativo</span></label></div><div class="inspector-body"><div class="inspector-grid"><label class="inspector-field"><span>Cor</span><input type="color" class="gis-input color-field" value="#334155"></label><label class="inspector-field"><span>Espessura · mm</span><input class="gis-input" value="0,25"></label></div><label class="inspector-field"><span>Traçado</span><select class="gis-select"><option>Tracejado</option></select></label></div></section><section class="inspector-card"><h4>Intensidade <span>100%</span></h4><div class="inspector-body"><input type="range" class="opacity-control" value="100"></div></section></div>';
            const p=document.getElementById('paper-sheet');composerDispose();p.replaceChildren();p.style.width=297*96/25.4+'px';p.style.height=210*96/25.4+'px';p.dataset.widthMm=297;p.dataset.heightMm=210;
            composerInitV3('paper-sheet',helper,null,{crsName:'UTM 23S',metersPerUnit:1,scale:5000,token:'fixture',centerX:0,centerY:0});
            const title=composerAddItemV3('Text','PLANTA DE LOCALIZAÇÃO',45,30,600,50);composerUpdateItemProperty(title,'FontSize',24);composerUpdateItemProperty(title,'FontWeight','bold');
            const map=composerAddItemV3('Map','Área de estudo',45,110,760,520);
            const canvas=document.createElement('canvas');canvas.width=760;canvas.height=520;const ctx=canvas.getContext('2d');ctx.fillStyle='#dfebdf';ctx.fillRect(0,0,760,520);ctx.strokeStyle='#99b7bf';ctx.lineWidth=16;ctx.beginPath();ctx.moveTo(0,310);ctx.lineTo(300,340);ctx.lineTo(760,80);ctx.stroke();ctx.strokeStyle='#82917a';ctx.lineWidth=1;
            for(let x=40;x<760;x+=80){ctx.strokeRect(x,45,55,90);ctx.strokeRect(x,390,55,90);}document.querySelector('#'+map+' img').src=canvas.toDataURL();
            const legend=composerAddItemV3('Text','LEGENDA\n\nÁrea de estudo\nHidrografia\nParcelamento',855,115,220,250);composerUpdateItemProperty(legend,'FontSize',17);
            composerAddItemV3('Image','Norte',920,450,60,90);composerAddItemV3('ScaleBar','Escala',45,675,300,50);
            const source=composerAddItemV3('Text','Prévia de interface • Dados sintéticos • SIRGAS 2000 / UTM 23S',45,748,1000,30);composerUpdateItemProperty(source,'FontSize',12);
            composerSelectItem(map);composerFitPage();
        });
        await page.screenshot({path:path.join(artifacts,'design-desktop.png')});
        await page.setViewportSize({width:1024,height:768});
        await page.evaluate(()=>composerFitPage());
        check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'notebook has no outer horizontal overflow');
        await page.screenshot({path:path.join(artifacts,'design-notebook.png')});
        check(errors, [], 'no uncaught browser errors');
        console.log(`${assertions} checks passed. Artifacts: ${artifacts}`);
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
